### ISSUE TITLE
Users Not Following Me feature is producing false positives.

### ISSUE THREAD

**Issue by Simon818** [masonasons/Quinter#3]
In latest source as of this writing, many of the people in the *Users Not Following Me* section of Quinter are in fact following me according to other clients. I see no pattern to it, so that's unfortunately all I've got, though I'm of course happy to test anything that can generate some debug logs.

**Comment by trypsynth** [comment]
Strange. Does the inverse happen? People you're following not show as you're following them?

**Comment by masonasons** [comment]
Hi Simon,The reason this happens is because Quinter is not able to retrieve all of your followers/friends. Try to increase the API calls in preferences/advanced and try again.   Sent from Mail for Windows 10 From: Simon JaegerSent: Friday, July 9, 2021 2:11 AMTo: masonasons/QuinterCc: SubscribedSubject: [masonasons/Quinter] Users Not Following Me feature is producing false positives. (#3) In latest source as of this writing, many of the people in the Users Not Following Me section of Quinter are in fact following me according to other clients. I see no pattern to it, so that's unfortunately all I've got, though I'm of course happy to test anything that can generate some debug logs.—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Simon818** [comment]
Thanks, I should have thought of that.

This still seems like a slight bug / enhancement to me, since Quinter could compare available API calls and max items with my follower / friend count and figure out whether it's likely to produce false positives or not. But I'm glad to have this working.

**Comment by masonasons** [comment]
Hi Simon, Yes, I did plan to do this.  Sent from Mail for Windows 10 From: Simon JaegerSent: Friday, July 9, 2021 3:29 PMTo: masonasons/QuinterCc: masonasons; CommentSubject: Re: [masonasons/Quinter] Users Not Following Me feature is producing false positives. (#3) Thanks, I should have thought of that.This still seems like a slight bug / enhancement to me, since Quinter could compare available API calls and max items with my follower / friend count and figure out whether it's likely to produce false positives or not. But I'm glad to have this working.—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
